"""
Configuration settings for the cryptocurrency price prediction project.
"""

CRYPTOCURRENCIES = ['BTC', 'ETH', 'SOL']
QUOTE_CURRENCY = 'USDT'
TIMEFRAME = '1m'  
START_DATE = '2023-12-01'  
END_DATE = '2024-12-01'    

BINANCE_BASE_URL = 'https://api.binance.com'
COINGECKO_BASE_URL = 'https://api.coingecko.com/api/v3'

MAX_GAP_MINUTES = 5  
IQR_MULTIPLIER = 3.0  
VOLUME_ZSCORE_WINDOW = 24 * 60  

LOG_RETURN_LAGS = [1, 5, 15]  
VOLATILITY_WINDOWS = [15, 60]  
RSI_PERIOD = 14  
LAGGED_RETURNS = [1, 5, 10]  

SEQUENCE_LENGTH = 60  
TRAIN_SPLIT = 0.7  
VAL_SPLIT = 0.15   
TEST_SPLIT = 0.15  

LSTM_UNITS = 64
LSTM_LAYERS = 2
LSTM_DROPOUT = 0.2
LSTM_DENSE_UNITS = [64, 32]
LSTM_LEARNING_RATE = 1e-3
LSTM_BATCH_SIZE = 64
LSTM_MAX_EPOCHS = 100

TRANSFORMER_DIM = 64
TRANSFORMER_HEADS = 4
TRANSFORMER_LAYERS = 2
TRANSFORMER_FF_DIM = 256
TRANSFORMER_LEARNING_RATE = 1e-4
TRANSFORMER_WEIGHT_DECAY = 1e-2
TRANSFORMER_BATCH_SIZE = 64
TRANSFORMER_MAX_EPOCHS = 100
